wandb_version: 1

ALAE:
  desc: null
  value: false
BATCH_SIZE:
  desc: null
  value: 64
BETAS:
  desc: null
  value:
  - 0.2
  - 0.99
CHI_PROJECTION:
  desc: null
  value: false
CLASSES:
  desc: null
  value:
  - 0
  - 1
  - 2
DATASET:
  desc: null
  value: ave_celeba
DATASET_PATH:
  desc: null
  value: ../../../data/ave_celeba_green_v2/
DEVICE:
  desc: null
  value: cuda:0
EPSILON:
  desc: null
  value: 1.0
FLAG_LATENT:
  desc: null
  value: true
GENERATOR_PATH:
  desc: null
  value: ../../../stylegan2_ada_pytorch_before/training-runs/00011-aligned_celeba-stylegan2/network-snapshot-008800.pkl
GPU_DEVICE:
  desc: null
  value: 0
HIDDEN_SIZE:
  desc: null
  value:
  - 1024
  - 1024
IMG_SIZE:
  desc: null
  value: 64
INNER_ITERATIONS:
  desc: null
  value: 10
K:
  desc: null
  value: 3
LAMBDAS:
  desc: null
  value:
  - 0.25
  - 0.5
  - 0.25
LATENT_ENCODER_SIZE:
  desc: null
  value: 256
LATENT_SIZE:
  desc: null
  value: 512
LR_ENCODER:
  desc: null
  value: 0.0001
LR_LATENT_MLP:
  desc: null
  value: 0.0001
LR_POTENTIAL:
  desc: null
  value: 0.0001
NAME_EXP:
  desc: null
  value: KL_EPS_1.0_ALAE_False_ENC_True_EPS_1.0
NC:
  desc: null
  value: 3
NUM_EPOCHS:
  desc: null
  value: 1
RESNET_D_ENCODER:
  desc: null
  value: true
SPHERE_PROJECTION:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.8.5
      5: 0.10.33
      8:
      - 1
      - 2
      - 5
