wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 128
BETAS:
  desc: null
  value:
  - 0.2
  - 0.99
CLASSES:
  desc: null
  value:
  - 0
  - 1
  - 2
CLIP_GRADS_NORM:
  desc: null
  value: false
DATASET:
  desc: null
  value: ave_celeba
DATASET_PATH:
  desc: null
  value: ../../../data/ave_celeba_green_v2/
DEVICE:
  desc: null
  value: cuda:0
DIM:
  desc: null
  value: 12288
FLAG_LATENT:
  desc: null
  value: false
FLAG_LATENT_CRITIC:
  desc: null
  value: false
GPU_DEVICE:
  desc: null
  value: 0
IMG_SIZE:
  desc: null
  value: 64
INNER_ITERATIONS:
  desc: null
  value: 10
K:
  desc: null
  value: 3
LAMBDAS:
  desc: null
  value:
  - 0.25
  - 0.5
  - 0.25
LR:
  desc: null
  value: 0.0001
NAME_EXP:
  desc: null
  value: L2_SPACE_INN_10_LR_0.0001_BS_128
NC:
  desc: null
  value: 3
NUM_EPOCHS:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.5
    t:
      1:
      - 1
      4: 3.8.5
      5: 0.10.33
      8:
      - 1
      - 2
      - 5
