wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 1000
CASE:
  desc: null
  value: Gaussians
_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      4: 3.8.5
      5: 0.10.33
      8:
      - 1
      - 2
      - 5
