wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 64
BETAS:
  desc: null
  value:
  - 0.2
  - 0.99
BRIGHTNESS:
  desc: null
  value: 1
CLASSES:
  desc: null
  value:
  - 2
DATASET:
  desc: null
  value: colored_mnist
DATASET_PATH:
  desc: null
  value: ../../../data/MNIST
DEVICE:
  desc: null
  value: cuda:0
EPSILON:
  desc: null
  value: 0.1
FLAG_LATENT:
  desc: null
  value: true
GENERATOR_PATH:
  desc: null
  value: ../../../stylegan2_ada_pytorch_before/ckpts/MNIST-colored_2_3/network-snapshot-002000.pkl
GPU_DEVICE:
  desc: null
  value: 0
HUE_MEAN:
  desc: null
  value: 120
HUE_MEANS:
  desc: null
  value:
  - 0
  - 60
  - 120
HUE_STD:
  desc: null
  value: 0.0
IMG_SIZE:
  desc: null
  value: 32
INNER_ITERATIONS:
  desc: null
  value: 10
K:
  desc: null
  value: 2
LAMBDAS:
  desc: null
  value:
  - 0.5
  - 0.5
LATENT_SIZE:
  desc: null
  value: 512
LR_ENCODER:
  desc: null
  value: 0.0001
LR_LATENT_MLP:
  desc: null
  value: 0.0001
LR_POTENTIAL:
  desc: null
  value: 0.0001
NAME_EXP:
  desc: null
  value: KL_EPS_0.1_LMBD_[0.5, 0.5]_mltp_100_THRESHOLD_0.8
NC:
  desc: null
  value: 1
NUMBER_PALETTES:
  desc: null
  value: 50000
NUM_EPOCHS:
  desc: null
  value: 1
SATURATION:
  desc: null
  value: 1
SATURATION_THRESHOLD:
  desc: null
  value: 0.8
_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.5
      5: 0.10.33
      8:
      - 1
      - 2
      - 5
