wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 32
BETAS:
  desc: null
  value:
  - 0.2
  - 0.99
DATASET:
  desc: null
  value: ave_celeba
DATASET_PATH:
  desc: null
  value: ../../../data/ave_celeba_green_v2/
DEVICE:
  desc: null
  value: cuda:0
FLAG_LATENT:
  desc: null
  value: true
GAMMA:
  desc: null
  value: 0.1
GENERATOR_PATH:
  desc: null
  value: ../../../stylegan2_ada_pytorch_before/training-runs/00011-aligned_celeba-stylegan2/network-snapshot-008800.pkl
GPU_DEVICE:
  desc: null
  value: 0
IMG_SIZE:
  desc: null
  value: 64
INNER_ITERATIONS:
  desc: null
  value: 10
K:
  desc: null
  value: 3
LAMBDAS:
  desc: null
  value:
  - 0.25
  - 0.5
  - 0.25
LATENT_SIZE:
  desc: null
  value: 512
LR_ENCODER:
  desc: null
  value: 0.0002
LR_POTENTIAL:
  desc: null
  value: 0.0002
NAME_EXP:
  desc: null
  value: Dist_GAMMA_0.1_Z_STD_0.1_BS_32_NZ_2
NC:
  desc: null
  value: 3
NUM_EPOCHS:
  desc: null
  value: 1
RESNET_ENCODER_LATENT:
  desc: null
  value: 2
WEIGHT_NORM:
  desc: null
  value: 0.1
ZC:
  desc: null
  value: 1
Z_STD:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.5
    t:
      1:
      - 1
      4: 3.8.5
      5: 0.10.33
      8:
      - 1
      - 2
      - 5
